name: LineageOS Build

on:
  workflow_dispatch:
    inputs:
      lineage_branch:
        description: "LineageOS branch (e.g. lineage-20.0)"
        required: false
        default: "lineage-20.0"
      build_target:
        description: "Build target (recoveryimage, bootimage, bacon, kernel)"
        required: false
        default: "recoveryimage"
      ccache_size:
        description: "Ccache size (e.g. 75G)"
        required: false
        default: "75G"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk git git-lfs curl wget bc bison build-essential \
            ccache flex gperf libncurses5-dev libssl-dev libxml2-utils \
            lzop python3 rsync unzip zip zlib1g-dev liblz4-tool aria2 \
            gnupg file
          git lfs install

          # install official Android repo tool
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

          # configure git identity for repo
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ github.ref }}
          restore-keys: |
            ccache-

      - name: Cache repo sources
        uses: actions/cache@v4
        with:
          path: .repo
          key: repo-${{ github.ref }}
          restore-keys: |
            repo-

      - name: Initialize and sync sources
        run: |
          export USE_CCACHE=1
          export CCACHE_DIR=$HOME/.ccache
          ccache -M "${{ github.event.inputs.ccache_size }}"

          echo ">>> Building LineageOS ${{ github.event.inputs.lineage_branch }} for cannong"
          echo ">>> Build target: ${{ github.event.inputs.build_target }}"
          echo ">>> Ccache size: ${{ github.event.inputs.ccache_size }}"

          rm -rf .repo
          repo init -u https://github.com/LineageOS/android.git -b ${{ github.event.inputs.lineage_branch }} --git-lfs
          ls -la .repo/manifests || echo "manifest missing"

          repo sync -c --no-tags --no-clone-bundle --depth=1 -j4 || \
          repo sync -c --no-tags --no-clone-bundle --depth=1 -j1

      - name: Build
        run: |
          source build/envsetup.sh
          lunch lineage_cannong-userdebug
          make ${{ github.event.inputs.build_target }} -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lineage-artifacts
          path: |
            out/target/product/cannong/recovery.img
            out/target/product/cannong/boot.img
            out/target/product/cannong/lineage-*.zip
            out/target/product/cannong/obj/KERNEL_OBJ/arch/arm64/boot/Image.gz-dtb
          if-no-files-found: ignore
